# Generated by Django 3.1.7 on 2021-05-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name_plural': 'Restaurants'},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='R_Email',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='R_Name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='R_Password',
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='F_Images',
            field=models.ImageField(default='null', upload_to='media/media'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='R_Image',
            field=models.ImageField(default='null', upload_to='media/media/images'),
        ),
    ]
