# Generated by Django 3.1.3 on 2021-05-09 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='R_Email',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='R_Name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='R_Password',
        ),
    ]
