# Generated by Django 3.1.7 on 2021-05-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocard',
            name='Customer_id',
        ),
        migrations.RemoveField(
            model_name='addtocard',
            name='Food_it_id',
        ),
        migrations.AddField(
            model_name='addtocard',
            name='descrip',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='addtocard',
            name='images',
            field=models.ImageField(default='null', upload_to='media/media/media/media'),
        ),
        migrations.AddField(
            model_name='addtocard',
            name='kind',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='addtocard',
            name='name',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='addtocard',
            name='prise',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='addtocard',
            name='size',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='F_Images',
            field=models.ImageField(default='null', upload_to='images'),
        ),
    ]
