# Generated by Django 3.1.7 on 2021-05-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0002_auto_20210512_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocard',
            name='images',
            field=models.ImageField(default='null', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='R_Image',
            field=models.ImageField(default='null', upload_to='images'),
        ),
    ]
