# Generated by Django 3.1.7 on 2021-05-13 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0003_auto_20210512_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocard',
            name='fooods',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='fastfoodapp.fooditem'),
        ),
    ]
