# Generated by Django 3.1.7 on 2021-05-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0003_restaurant_r_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='It_Prise',
            field=models.IntegerField(default=0),
        ),
    ]
