# Generated by Django 3.1.7 on 2021-05-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0004_addtocard_fooods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocard',
            name='fooods',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fastfoodapp.fooditem'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='restaurants',
        ),
        migrations.AddField(
            model_name='order',
            name='restaurants',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='fastfoodapp.restaurant'),
        ),
    ]
