# Generated by Django 3.1.7 on 2021-05-10 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0004_auto_20210510_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='It_Prise',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
