# Generated by Django 3.1.7 on 2021-05-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0008_auto_20210511_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='F_Images',
            field=models.ImageField(default='null', upload_to='media/media/media/media'),
        ),
    ]
