# Generated by Django 3.1.7 on 2021-05-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0009_auto_20210511_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='It_Prise',
            field=models.IntegerField(default=0),
        ),
    ]
