# Generated by Django 3.1.7 on 2021-05-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0010_auto_20210511_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='It_Prise',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
