# Generated by Django 3.1.7 on 2021-05-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0010_auto_20210518_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addtocard',
            name='meal',
        ),
        migrations.AddField(
            model_name='addtocard',
            name='meal',
            field=models.ManyToManyField(default=0, to='fastfoodapp.FoodItem'),
        ),
        migrations.RemoveField(
            model_name='addtocard',
            name='restaurnt_id',
        ),
        migrations.AddField(
            model_name='addtocard',
            name='restaurnt_id',
            field=models.ManyToManyField(default=0, to='fastfoodapp.Restaurant'),
        ),
    ]
