# Generated by Django 3.1.7 on 2021-05-11 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0011_auto_20210511_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addtocard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='fastfoodapp.customer')),
                ('Food_it_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='fastfoodapp.fooditem')),
            ],
        ),
    ]
