# Generated by Django 3.1.7 on 2021-05-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0011_auto_20210518_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocard',
            name='orders_Name',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
