# Generated by Django 3.1.7 on 2021-05-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0056_auto_20210508_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='F_Images',
            field=models.ImageField(default='static/fastfoodapp/images/nullImage.jfif', upload_to='static/fastfoodapp/images'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='RImage_Cover',
            field=models.ImageField(default='static/fastfoodapp/images/nullImage.jfif', upload_to='static/fastfoodapp/images'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='R_Image',
            field=models.ImageField(default='static/fastfoodapp/images/nullImage.jfif', upload_to='static/fastfoodapp/images'),
        ),
    ]
