# Generated by Django 3.1.7 on 2021-05-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0057_auto_20210508_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='F_Images',
            field=models.ImageField(default='media/images/null.png', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='RImage_Cover',
            field=models.ImageField(default='null', upload_to='media/images'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='R_Image',
            field=models.ImageField(default='null', upload_to='media/images'),
        ),
    ]
