# Generated by Django 3.1.7 on 2021-05-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0061_auto_20210509_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='F_Images',
            field=models.ImageField(default='FastFood/media/media/images/null.png', upload_to='media/media/images'),
        ),
    ]
