# Generated by Django 3.1.7 on 2021-05-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastfoodapp', '0063_auto_20210509_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='F_Images',
            field=models.ImageField(default='null', upload_to='media/media'),
        ),
    ]
